name: masiv
channels:
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pytorch
  - pytorch-cuda=12.4
  - torchvision
  - pip:
      - numpy<2
      - dearpygui
      - imageio
      - imageio-ffmpeg
      - lpips
      - ninja
      - open3d
      - opencv-python
      - plyfile
      - scipy
      - taichi==1.7.4
      - tqdm
      - trimesh
      - einops
      - kornia==0.8.2
      - omegaconf
      - warp-lang==1.7.2

